# Generated by Django 3.1 on 2020-11-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201113_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abertura',
            name='dataFechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
